<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Sources/ThinCam/ThinCam.csproj" AdditionalProperties="ThinCamTargetFrameworks=net8.0" />
    <ProjectReference Include="../../Sources/ThinCam.SkiaSharp/ThinCam.SkiaSharp.csproj" AdditionalProperties="ThinCamTargetFrameworks=net8.0" />
    <ProjectReference Include="../../Sources/ThinCam.Avalonia/ThinCam.Avalonia.csproj" AdditionalProperties="ThinCamTargetFrameworks=net8.0" />
  </ItemGroup>
</Project>
